export type Repository = {
  id: string;
  Timestamp: string;
  score: string;
  year_of_study: string;
  concentrations: string;
  hours_per_week_visual_design: string;
  activities_resources_used: string;
  access_to_resources: string;
  curriculum_expectations: string;
  visual_design_expectations: string;
  visual_design_competency: string;
  typography_skills: string;
  color_theory_skills: string;
  layout_composition_skills: string;
  digital_illustration_skills: string;
  ui_design_skills: string;
  ux_design_skills: string;
  prototyping_mockup_skills: string;
  confidence_in_design_decisions: string;
  creative_person_self_assessment: string;
  problem_solving_confidence: string;
  trust_in_creative_abilities: string;
  imagination_distinction: string;
  frequency_of_ai_tool_use: string;
  ai_tasks_types: string;
  ai_tools_efficiency: string;
  confidence_in_ai_output_quality: string;
  ai_feedback_usefulness: string;
  ai_future_influence_on_skills: string;
  confidence_in_ai_design_decisions: string;
  "Are you an international student?": string;
  "If you are an international student, what is your country of origin?": string;
  "What is your SFU email address? (We cannot send the $50 raffle prize without this information. Please leave n/a if you are not interested)": string;
  "Complete the statement: As an undergraduate student, I am hoping to complete a...": string;
  "How did you hear about this survey?": string;
  confidence_score: string;
  visual_confidence_score: string;
  creative_self_e_score: string;
  confidence_in_ai_score: string;
  score_percent: string;
};
